mp.jwt.signer.key-location=privateKey.pem
mp.jwt.verify.issuer=http://localhost:8080
smallrye.jwt.sign.key-location=privateKey.pem
quarkus.http.root-path=/api


quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=quarkus
quarkus.datasource.password=quarkus
quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/rapportdb

## devs !! move to test properties
%dev.quarkus.hibernate-orm.database.generation=drop-and-create
%dev.quarkus.hibernate-orm.log.sql=true
%dev.quarkus.hibernate-orm.log.format-sql=true
%dev.quarkus.hibernate-orm.log.bind-parameters=true


#dev
quarkus.http.cors.enabled=true 
quarkus.http.cors.origins=http://localhost:4200
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type
