quarkus.http.root-path=/api

#jwt config
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=http://localhost:8080
smallrye.jwt.sign.key.location=privateKey.pem
rpp.token.duration=PT1H

## devs mode
%dev.quarkus.hibernate-orm.database.generation=drop-and-create
%dev.quarkus.hibernate-orm.log.sql=true
%dev.quarkus.hibernate-orm.log.format-sql=true
%dev.quarkus.hibernate-orm.log.bind-parameters=true
